### ISSUE TITLE
Changelog in addon updates

### ISSUE THREAD

**Issue by backslashV** [NickM-27/swatch-hass-addon#1]
Hi,

Can you please include the changelog in the HA addon updates?

**Comment by NickM-27** [comment]
My bad, I thought it just needed a changelog but they need to be inside each specific addon (stable and beta).

**Comment by backslashV** [comment]
I just noticed that the addon shows update notification for one version above the current release.
![image](https://user-images.githubusercontent.com/8752221/172754948-565a1ca6-3d0f-440c-9c1e-3f23ab8a5d21.png)

**Comment by NickM-27** [comment]
It's a naming thing. I had to update something in the addon directly so I increased it so it's slightly out of sync
